"""Renders docs/transformation_catalog.md from the Silver specs, so the catalog always matches the code.

    python -m scripts.build_docs
"""

from __future__ import annotations

from src.common.config import Config
from src.common.schemas import EVENT_TIME_COLUMNS, SOURCE_SCHEMAS
from src.quality.rules import ISSUE_FOR_CATEGORY
from src.quality.standardize import TIMESTAMP_FORMATS
from src.transformations.silver.engine import LINEAGE
from src.transformations.silver.run import BULK_ORDER_QUANTITY, LOOKUP_PARENTS
from src.transformations.silver.specs import CITY, SILVER_ORDER, SPECS

LOOKUP_DOCS = {
    "order_items": "catalog price from `slv_products` (for the unit-price check)",
    "order_promotions": "order business date from `slv_orders`; promotion start/end from `slv_promotions`",
    "payments": "order's stored total from `slv_orders` and its recomputed total (see orders post-processing)",
    "deliveries": "rider's city from `slv_delivery_partners`; store city via `slv_orders` → `slv_stores`",
    "cancellations": "`order_ts` from `slv_orders`",
    "reviews": "purchased (order, product) pairs from the de-duplicated order items; whether any of the order's "
               "item rows were rejected",
    "returns_refunds": "amount and `payment_ts` of the refunded payment from `slv_payments`",
}

DERIVED_DOCS = {
    "computed_total_amount": "Σ(quantity × catalog price) of the order's Silver lines − its Silver discount; empty "
                             "when any of the order's item or promotion rows was rejected (cannot recompute)",
    "dq_total_mismatch": "true when `total_amount` ≠ `computed_total_amount` (> ₹0.005); empty when it cannot be "
                         "recomputed. Typical cause: a line was lost or the total was altered",
    "is_outlier": f"true when any line of the order has quantity ≥ {BULK_ORDER_QUANTITY} (bulk order; normal "
                  "lines are 1–5). Kept, not rejected",
    "is_completed": "shared eligibility rule: `status` = delivered AND a successful payment exists in "
                    "`slv_payments` AND no cancellation exists in `slv_cancellations`",
    "line_amount": "round(quantity × unit_price, 2)",
    "delivery_minutes": "(delivered_ts − pickup_ts) in minutes, 1 decimal; only for delivered rows",
    "platform": "`metadata.platform` (android / ios / web)",
    "app_version": "`metadata.app_version`",
    "dq_email_invalid": "true when the email failed the format check; the email was blanked (customer kept)",
}

STEPS = [
    ("1. Separate unparseable rows", "Rows Spark could not parse in Bronze (`_corrupt_record` set)",
     "quarantine, rule `malformed:row`"),
    ("2. Standardise", "Trim every string; empty → null; casing rules per dataset (below)", "values fixed in place"),
    ("3. Parse & cast", "Strings → int / decimal(12,2) / double / timestamp / date. Timestamps accept "
     + ", ".join(f"`{f}`" for f in TIMESTAMP_FORMATS) + " (all UTC)",
     "present-but-unparseable value → `type_invalid:<col>`"),
    ("4. Remove duplicates", "One row per business key; keep latest `_ingestion_ts`, then latest event time, then "
     "highest `_record_hash`. Rows without a full key skip this step", "extra copies removed (counted)"),
    ("5. Validate", "Required values, types, allowed values, ranges, time order, business rules, foreign keys "
     "against already-accepted parent tables", "list of failed rules per row"),
    ("6. Split", "Any hard rule failed → quarantine (`direct`, or `cascade` when the only failure is a rejected "
     "parent). Soft rules → `dq_*` flag on the kept row", "Silver / quarantine"),
    ("7. Derive", "Add helper columns (business date, line amount, …)", "extra Silver columns"),
]

CATEGORY_DOCS = {
    "malformed": "row or JSON payload cannot be parsed",
    "required_missing": "a required value is empty",
    "type_invalid": "a value is present but not a valid number / date / timestamp",
    "enum_invalid": "a code value is outside the allowed list even after standardisation",
    "range_invalid": "a number is outside its valid range",
    "sequence_invalid": "timestamps are in an impossible order",
    "fk_missing": "a referenced parent does not exist at all",
    "business": "a business rule is violated (soft flag, except refund > payment)",
    "parent_rejected": "the referenced parent exists but was itself quarantined (cascade)",
}


def _md(text: str) -> str:
    return text.replace("|", "\\|")


def _allowed(values: tuple[str, ...], cities: tuple[str, ...]) -> str:
    vals = cities if values == (CITY,) else values
    return ", ".join(f"`{v}`" for v in vals)


def render_catalog(cfg: Config) -> str:
    cities = tuple(c.city_id for c in cfg.cities)
    out: list[str] = []
    w = out.append
    w("# Transformation Catalog — Bronze → Silver")
    w("")
    w("> Generated by `python -m scripts.build_docs` from `src/transformations/silver/specs.py` and the Silver engine. "
      "Do not edit by hand. The narrative (why, results, problems found) is in `03_silver_transformations.md`.")
    w("")
    w("Silver turns each Bronze table (raw strings, ~10% dirty) into a typed, standardised, de-duplicated table "
      "`data/silver/slv_<dataset>/`. Rejected rows go to `data/quarantine/qtn_records/<dataset>/` with the rules they "
      "failed. Silver is rebuilt in full on every run (CSV storage, no in-place updates).")
    w("")
    w("## The seven steps (every dataset)")
    w("")
    w("| Step | What happens | Outcome |")
    w("|---|---|---|")
    for step, what, outcome in STEPS:
        w(f"| {step} | {_md(what)} | {_md(outcome)} |")
    w("")
    w("## Rule categories")
    w("")
    w("Rules are named `<category>:<detail>`. When a row fails several, `primary_rule` is the first by this order.")
    w("")
    w("| Priority | Category | Meaning | Outcome | Detects injected issue |")
    w("|:-:|---|---|---|---|")
    for i, cat in enumerate(CATEGORY_DOCS, start=1):
        outcome = {"business": "flag (`dq_*`), quarantine only if hard", "parent_rejected": "quarantine (cascade)"}.get(
            cat, "quarantine (direct)")
        w(f"| {i} | `{cat}` | {CATEGORY_DOCS[cat]} | {outcome} | {ISSUE_FOR_CATEGORY[cat]} |")
    w("")
    w("Duplicates (DUP) are removed in step 4 and format issues (FMT) are fixed in steps 2–3; neither is quarantined.")
    w("")
    w("## Processing order")
    w("")
    w("Parents are built before children so foreign keys are checked against accepted parent rows:")
    w("")
    for i, ds in enumerate(SILVER_ORDER, start=1):
        parents = sorted({fk.parent for fk in SPECS[ds].fks})
        w(f"{i}. `{ds}`" + (f" (after {', '.join(f'`{p}`' for p in parents)})" if parents else ""))
    w("")
    w("Then **orders post-processing** fills the order columns that need child tables (see `orders`).")
    w("")
    w("## Quarantine record (`qtn_records`)")
    w("")
    w("| Column | Meaning |")
    w("|---|---|")
    for col, meaning in [
        ("source_dataset", "dataset the row came from"),
        ("source_record_id", "business key as `col=value;…` (empty value if the key itself was missing)"),
        ("failed_rules", "every failed hard rule, `|`-separated"),
        ("primary_rule", "the highest-priority failed rule"),
        ("severity", "`error` (direct) or `warning` (cascade)"),
        ("rejection_type", "`direct` (the row broke a rule) or `cascade` (only its parent was rejected)"),
        ("raw_record", "the original Bronze values as JSON"),
        ("bronze_batch_id, source_file", "where the row came from"),
        ("silver_run_id, rejected_at", "which run rejected it, and when"),
    ]:
        w(f"| `{col}` | {meaning} |")
    w("")
    w("## Lineage (table level)")
    w("")
    w("| Target | Built from |")
    w("|---|---|")
    for ds in SILVER_ORDER:
        parents = sorted({fk.parent for fk in SPECS[ds].fks} | set(LOOKUP_PARENTS.get(ds, [])))
        sources = [f"`brz_{ds}`"] + [f"`slv_{p}`" for p in parents if p != ds]
        w(f"| `slv_{ds}` | {', '.join(sources)} |")
    w("| `qtn_records` | every `brz_<dataset>` (rejected rows) |")
    w("")
    w("---")
    w("")

    for ds in SILVER_ORDER:
        spec, schema = SPECS[ds], SOURCE_SCHEMAS[ds]
        w(f"## {ds}")
        w("")
        w(f"`brz_{ds}` → `slv_{ds}` (+ rejected rows → `qtn_records/{ds}`). "
          f"**Business key:** `{', '.join(schema.business_key)}`. "
          f"**Duplicate tie-break:** latest `_ingestion_ts`"
          + (f", then latest `{EVENT_TIME_COLUMNS[ds]}`" if ds in EVENT_TIME_COLUMNS else "")
          + ", then highest `_record_hash`.")
        w("")
        std = ["trim all text columns (blank → empty)"]
        if spec.lower:
            std.append("lowercase " + ", ".join(f"`{c}`" for c in spec.lower))
        if spec.upper:
            std.append("uppercase " + ", ".join(f"`{c}`" for c in spec.upper))
        if spec.initcap:
            std.append("Title Case " + ", ".join(f"`{c}`" for c in spec.initcap))
        if spec.majority:
            std.append("most frequent spelling for " + ", ".join(f"`{c}`" for c in spec.majority)
                       + " (case-insensitive groups)")
        if spec.email:
            std.append("lowercase " + ", ".join(f"`{c}`" for c in spec.email) + "; invalid format → blank + `dq_email_invalid`")
        w("**Standardise:** " + "; ".join(std) + ".")
        typed = [f"`{c.name}` → {c.dtype}" for c in schema.columns if c.dtype != "string"]
        if typed:
            w("")
            w("**Cast:** " + ", ".join(typed) + ".")
        w("")
        w("| Rule | Kind | Outcome | Description |")
        w("|---|---|---|---|")
        required = [c.name for c in schema.columns if not c.nullable]
        w(f"| `required_missing:<col>` | hard | quarantine | required: {', '.join(f'`{c}`' for c in required)} |")
        if typed:
            w("| `type_invalid:<col>` | hard | quarantine | value present but not parseable as its type |")
        for col, allowed in spec.enums.items():
            w(f"| `enum_invalid:{col}` | hard | quarantine | allowed: {_allowed(allowed, cities)} |")
        for rule in spec.rules:
            outcome = "quarantine" if rule.hard else f"flag `{rule.flag_column}`"
            if not rule.hard and not rule.unknown_is_pass:
                outcome += " (empty = could not verify)"
            w(f"| `{rule.name}` | {'hard' if rule.hard else 'soft'} | {outcome} | {_md(rule.description)} |")
        for fk in spec.fks:
            w(f"| `fk_missing:{fk.column}` | hard | quarantine | `{fk.column}` must exist in "
              f"`slv_{fk.parent}.{fk.parent_column}` |")
            w(f"| `parent_rejected:{fk.parent}` | hard | quarantine (cascade) | the referenced `{fk.parent}` row was "
              "quarantined |")
        w("")
        if ds in LOOKUP_DOCS:
            w(f"**Lookups:** {LOOKUP_DOCS[ds]}.")
            w("")
        if spec.derived:
            w("**Derived columns:**")
            w("")
            w("| Column | Type | Definition |")
            w("|---|---|---|")
            for col, dtype in spec.derived:
                doc = DERIVED_DOCS.get(col) or (f"date in Asia/Kolkata of `{EVENT_TIME_COLUMNS[ds]}`"
                                                if col == "business_date" else "")
                w(f"| `{col}` | {dtype} | {_md(doc)} |")
            w("")
        if ds == "orders":
            w("**Orders post-processing** (after order items, promotions, payments and cancellations are built): fills "
              "`computed_total_amount`, `dq_total_mismatch`, `is_outlier`, `is_completed` as defined above.")
            w("")
        w(f"**Lineage columns:** {', '.join(f'`{c}`' for c in LINEAGE)}.")
        w("")
    return "\n".join(out)
