"""Renders docs/gold_catalog.md and docs/metric_definitions.md from the Gold declarations and METRICS."""

from __future__ import annotations

from src.serving.metrics import METRICS
from src.transformations.gold.run import GOLD_TABLES


def _md(text: str) -> str:
    return text.replace("|", "\\|")


def render_metric_definitions() -> str:
    out = ["# Metric Definitions", "",
           "> Generated by `python -m scripts.build_docs` from `src/serving/metrics.py`. Do not edit by hand.", "",
           "Every business metric is defined once here and computed once in Gold. Dashboards and the business "
           "assistant read the Gold columns; they never recompute metrics.", "",
           "**Decisions (agreed 2026-10-04):** line revenue uses the catalog price when a line's unit price was "
           "flagged as a mismatch; only completed orders count toward revenue; only completed refunds are "
           "subtracted, on the refund's business date.", "",
           "| Metric | Definition | Formula |", "|---|---|---|"]
    out += [f"| **{m.name}** | {_md(m.definition)} | {_md(m.formula)} |" for m in METRICS]
    return "\n".join(out)


def render_gold_catalog() -> str:
    out = ["# Gold Catalog", "",
           "> Generated by `python -m scripts.build_docs` from `src/transformations/gold/`. Do not edit by hand. "
           "The narrative (why, results, problems found) is in `04_gold.md`; metric formulas are in "
           "`metric_definitions.md`.", "",
           "Gold tables are business-ready: one fixed grain per table (what one row means), shared metric "
           "definitions, typed CSV in `data/gold/<table>/`, rebuilt in full from Silver on every run.", "",
           "| Table | Tier | Grain | Description |", "|---|:-:|---|---|"]
    for t in GOLD_TABLES:
        out.append(f"| [`{t.name}`](#{t.name}) | {t.tier} | {' × '.join(t.grain)} | {_md(t.description)} |")
    out += ["", "## Lineage", "", "| Gold table | Built from |", "|---|---|"]
    for t in GOLD_TABLES:
        out.append(f"| `{t.name}` | {', '.join(f'`{s}`' for s in t.sources)} |")
    out.append("")
    for t in GOLD_TABLES:
        out += ["---", "", f"## {t.name}", "", t.description, "",
                f"**Grain:** {', '.join(f'`{g}`' for g in t.grain)} · **Tier:** {t.tier} · "
                f"**Sources:** {', '.join(f'`{s}`' for s in t.sources)}", "",
                "| Column | Type | Description |", "|---|---|---|"]
        for c in t.columns:
            key = " 🔑" if c.name in t.grain else ""
            out.append(f"| `{c.name}`{key} | {c.dtype} | {_md(c.description)} |")
        out.append("")
    return "\n".join(out)
