"""File registry: what every project file is for, what it reads and what it produces.

Rendered to docs/file_registry.md by `python -m scripts.build_docs`. tests/unit/test_file_registry.py fails when
a code, config or test file is missing from REGISTRY or an entry points to a file that no longer exists, so every
new file must be registered when it is created (package markers `__init__.py` are skipped).
"""

from __future__ import annotations

from dataclasses import dataclass

TRACKED_GLOBS = ("configs/*.yaml", "src/**/*.py", "app/**/*.py", "scripts/*.py", "tests/**/*.py")


def tracked_files(root) -> set[str]:
    """Every project file that must have a registry entry (package markers excluded)."""
    found = set()
    for pattern in TRACKED_GLOBS:
        for path in root.glob(pattern):
            if path.name != "__init__.py" and "__pycache__" not in path.parts:
                found.add(path.relative_to(root).as_posix())
    return found


def _group(path: str) -> str:
    return max((g for g in GROUPS if path == g or path.startswith(g + "/")), key=len)


def render_file_registry() -> str:
    def md(text: str) -> str:
        return text.replace("|", "\\|")

    out = ["# File Registry", "",
           "> Generated by `python -m scripts.build_docs` from `src/common/file_registry.py`. Do not edit by hand. "
           "A test fails if a project file is missing here or an entry points to a deleted file.", "",
           "What every file is for, what it reads, what it produces, who uses it, and how to run it. "
           f"**{len(REGISTRY)} files.** Package markers (`__init__.py`) are omitted.", ""]
    for group, title in GROUPS.items():
        entries = [e for e in REGISTRY if _group(e.path) == group]
        if not entries:
            continue
        out += [f"## {title}", "", "| File | Phase | Purpose | Inputs | Outputs | Used by |", "|---|:-:|---|---|---|---|"]
        for e in entries:
            run = f"<br>`{e.run}`" if e.run else ""
            out.append(f"| `{e.path}` | {e.phase} | {md(e.purpose)}{run} | {md(e.inputs)} | {md(e.outputs)} | "
                       f"{md(e.used_by)} |")
        out.append("")
    return "\n".join(out)


@dataclass(frozen=True)
class FileEntry:
    path: str
    phase: str
    purpose: str
    inputs: str = "—"
    outputs: str = "—"
    used_by: str = "—"
    run: str = ""


GROUPS = {
    "configs": "Configuration",
    "src/common": "Shared foundations (config, schemas, I/O, Spark, docs)",
    "src/generation": "Phase 1 — Synthetic data generation",
    "src/ingestion": "Phase 2 — Bronze ingestion",
    "src/quality": "Phase 2 — Data-quality rules and standardisation",
    "src/transformations/silver": "Phase 2 — Silver transformations",
    "src/transformations/gold": "Phase 3 — Gold tables",
    "src/ml": "Phases 4–5 — Machine learning and analytics",
    "src/rag": "Phase 6 — Business assistant (RAG)",
    "src/orchestration": "Pipeline orchestration, tracking, publishing",
    "src/serving": "App data layer (DuckDB, queries, permissions, metrics)",
    "app": "Streamlit application",
    "scripts": "Command-line scripts",
    "tests": "Tests",
}

REGISTRY: tuple[FileEntry, ...] = (
    # ------------------------------------------------------------------ configs
    FileEntry("configs/default.yaml", "1", "Settings shared by every profile: seed, calendar, ingestion slices, ML split, "
              "paths, CSV conventions, ratios, demand model, personas, planted signals, holidays",
              "—", "loaded as the base of every Config", "src/common/config.py"),
    FileEntry("configs/small.yaml", "1", "Fast profile (~14K rows, 30 days, 3 stores) for tests and CI",
              "—", "profile overrides", "tests, generator --profile small"),
    FileEntry("configs/medium.yaml", "1", "Demo profile (~298K generated rows, 6 months, 12 stores)",
              "—", "profile overrides", "generator --profile medium"),
    FileEntry("configs/large.yaml", "1", "Benchmark-only profile (~3M rows, 30 stores)", "—", "profile overrides",
              "generator --profile large"),
    FileEntry("configs/dirty_data.yaml", "1", "Dirty-data budget: 90% clean, issue shares, which issue applies to which "
              "dataset, the concrete mutations, and valid behaviour outside the budget (late rows, optional nulls)",
              "—", "Config.dirty", "src/generation/dirty_data.py, landing.py, customers.py"),
    FileEntry("configs/cities.yaml", "1", "The 3 cities (id, name, state, coordinates, climate) and store placement radius",
              "—", "Config.cities", "reference data, weather, Silver city checks"),

    # ------------------------------------------------------------------ src/common
    FileEntry("src/common/paths.py", "1", "Project root and project-relative path resolution (no hard-coded paths)",
              "—", "PROJECT_ROOT, resolve()", "everything"),
    FileEntry("src/common/config.py", "1", "Load and validate configuration (Pydantic); derive per-dataset row targets",
              "configs/*.yaml", "Config object, derived_targets()", "generator, pipeline, scripts"),
    FileEntry("src/common/schemas.py", "1", "The 19 source schemas (columns, types, nullability, business keys) and "
              "Bronze column layout; event-time and source-system maps", "—",
              "SOURCE_SCHEMAS, bronze_columns()", "generator, Bronze, Silver, docs"),
    FileEntry("src/common/io.py", "1", "Pandas-side table I/O: CSV formatting, atomic writes with retry, typed reads",
              "DataFrames / CSV files", "CSV files, typed DataFrames", "generator, ML stage, publish, scripts"),
    FileEntry("src/common/spark.py", "2", "The single place a SparkSession is created; Windows setup (winutils, "
              "worker Python, short paths)", "tools/hadoop/bin", "SparkSession", "pipeline stages ingest/silver/gold, tests"),
    FileEntry("src/common/spark_io.py", "2", "Spark-side table I/O: explicit-schema CSV reads, whitespace-preserving "
              "writes, staging → rename", "CSV folders", "Spark DataFrames, CSV table folders", "Bronze, Silver, Gold"),
    FileEntry("src/common/data_dictionary.py", "1", "Column descriptions of every source dataset and Bronze metadata "
              "column", "schemas, configs", "docs/data_dictionary.md (via build_docs)", "scripts/build_docs.py"),
    FileEntry("src/common/file_registry.py", "5", "This registry: purpose / inputs / outputs of every project file",
              "—", "docs/file_registry.md (via build_docs)", "scripts/build_docs.py, tests"),

    # ------------------------------------------------------------------ src/generation
    FileEntry("src/generation/context.py", "1", "Shared generator state: per-component reproducible RNGs, calendar, "
              "ID and split helpers", "Config", "GenContext", "every generator module"),
    FileEntry("src/generation/reference.py", "1", "Categories, products (Zipf popularity, focus SKUs), stores, delivery "
              "partners, promotions", "Config", "ReferenceData", "generate_all.py"),
    FileEntry("src/generation/customers.py", "1", "Customers with hidden personas", "Config",
              "customers frame; gt_personas", "generate_all.py"),
    FileEntry("src/generation/weather.py", "1", "3-hourly weather per city with a monsoon pattern", "Config",
              "weather frame, daily rain matrix", "orders (demand), generate_all.py"),
    FileEntry("src/generation/anomalies.py", "1", "Plan the 15 planted anomalies (outages, demand spikes, gateway "
              "failures)", "reference data", "AnomalyPlan; gt_anomalies", "orders, downstream, events"),
    FileEntry("src/generation/orders.py", "1", "Orders and baskets from the demand model (store-day allocation, "
              "customers, hours, basket sizes, categories, products, planted pairs)",
              "reference, customers, weather, anomaly plan", "OrderBook; gt_affinity_pairs", "inventory.py, downstream.py"),
    FileEntry("src/generation/inventory.py", "1", "Minute-level stock simulation for focus SKUs: depletion, restocks, "
              "damage, planted stockout episodes, substitution", "OrderBook",
              "snapshots, inventory events, adjusted baskets; gt_stockouts", "downstream.py"),
    FileEntry("src/generation/downstream.py", "1", "Order items, promotions, payments, deliveries, cancellations, "
              "refunds, reviews — consistent with orders (rules C1–C11)", "OrderBook, inventory result",
              "Transactions", "generate_all.py"),
    FileEntry("src/generation/events.py", "1", "App clickstream events and service logs (incl. gateway-failure ERROR "
              "bursts)", "transactions, anomaly plan", "app events, logs frames", "generate_all.py"),
    FileEntry("src/generation/dirty_data.py", "1", "Inject the dirty-data budget into one dataset (exactly 90% clean); "
              "record every injected issue", "clean string frame, configs/dirty_data.yaml",
              "dirty rows, issue log", "generate_all.py"),
    FileEntry("src/generation/landing.py", "1", "Split a dataset into historical / batch / stream landing files with "
              "late and out-of-order arrivals", "dirty rows", "landing CSV files", "generate_all.py"),
    FileEntry("src/generation/manifest.py", "1", "Write the generation manifest and ground-truth files",
              "generation results", "manifest/*.csv, ground_truth/*.csv", "generate_all.py"),
    FileEntry("src/generation/generate_all.py", "1", "Run every generator for one run and write all outputs",
              "configs", "data/generation/<run_id>/{landing, manifest, ground_truth}, LATEST", "users, tests",
              "python -m src.generation.generate_all --profile medium"),

    # ------------------------------------------------------------------ src/ingestion
    FileEntry("src/ingestion/file_tracker.py", "2", "Discover landing files; SHA-256 identity; which files are already "
              "loaded", "landing folders, meta_file_loads", "LandingFile list, loaded identities", "bronze.py"),
    FileEntry("src/ingestion/bronze_writer.py", "2", "Add ingestion metadata (_batch_id, _source_file, _record_hash, "
              "_is_late, …) and write one Bronze batch", "raw string rows", "brz_<dataset>/batch=<id>/",
              "batch.py, stream.py"),
    FileEntry("src/ingestion/batch.py", "2", "Historical backfill, daily batch and log ingestion", "landing CSVs",
              "Bronze batches", "bronze.py"),
    FileEntry("src/ingestion/stream.py", "2", "Simulated stream ingestion with Spark Structured Streaming "
              "(micro-batches, checkpoint, late / watermark flags)", "landing/stream CSVs", "Bronze batches",
              "bronze.py"),
    FileEntry("src/ingestion/bronze.py", "2", "The ingest stage: guard one generation run, then batch + stream",
              "generation run", "data/bronze/", "pipeline stage ingest"),

    # ------------------------------------------------------------------ src/quality
    FileEntry("src/quality/rules.py", "2", "Data-quality rule model (hard / soft), range / sequence / business rule "
              "builders, rule priority", "—", "Rule objects", "Silver specs and engine"),
    FileEntry("src/quality/standardize.py", "2", "Trim, casing, majority spelling, 5-format timestamp parsing, casts, "
              "business date", "Spark columns", "standardised columns", "Silver engine, Gold"),

    # ------------------------------------------------------------------ src/transformations/silver
    FileEntry("src/transformations/silver/specs.py", "2", "Declarative Silver rules per dataset (casing, allowed values, "
              "ranges, FKs, business rules, lookups, derived columns) and processing order",
              "—", "SPECS, SILVER_ORDER", "engine.py, run.py, catalog.py"),
    FileEntry("src/transformations/silver/engine.py", "2", "The 7 Silver steps for one dataset (corrupt rows, "
              "standardise, cast, dedup, validate, split, derive); typed Silver reader",
              "Bronze table", "valid rows, quarantine rows, metrics", "run.py, Gold"),
    FileEntry("src/transformations/silver/run.py", "2", "The silver stage: build all 19 datasets in order, orders "
              "post-processing, write, metrics, lineage", "data/bronze/",
              "data/silver/slv_*, data/quarantine/qtn_records/*, meta_quality_results", "pipeline stage silver"),
    FileEntry("src/transformations/silver/catalog.py", "2", "Render the Bronze → Silver transformation catalog",
              "Silver specs", "docs/transformation_catalog.md (via build_docs)", "scripts/build_docs.py"),

    # ------------------------------------------------------------------ src/transformations/gold
    FileEntry("src/transformations/gold/base.py", "3", "Gold table declarations (grain, columns, sources) and the shared "
              "build context (calendar, order lines, order facts, refunds)", "Silver tables",
              "GoldTable, GoldContext", "every Gold table module, ML tables"),
    FileEntry("src/transformations/gold/sales.py", "3", "Daily sales, daily category sales, product performance",
              "slv_orders, order_items, products, promotions, refunds", "gld_daily_sales, gld_daily_category_sales, "
              "gld_product_performance", "gold run, forecasting, Business workspace"),
    FileEntry("src/transformations/gold/inventory.py", "3", "Daily stock per store × focus SKU rebuilt from weekly "
              "counts + events − sales, with reconciliation gap", "slv_inventory_snapshots, inventory_events, "
              "order lines, cancellations", "gld_inventory_daily", "features, stockout risk, lost sales, explorer"),
    FileEntry("src/transformations/gold/features.py", "3", "Leakage-safe forecasting features per store × category × day",
              "gld_daily_category_sales, gld_inventory_daily, slv_weather", "gld_demand_features", "forecasting"),
    FileEntry("src/transformations/gold/customers.py", "3", "Customer 360, customer × category spend, basket pairs",
              "Silver orders, items, products, promotions, reviews", "gld_customer_360, gld_customer_category, "
              "gld_basket_pairs", "segmentation, recommendations, basket rules"),
    FileEntry("src/transformations/gold/operations.py", "3", "Delivery, cancellation and promotion metrics; quality "
              "summary", "Silver deliveries, cancellations, promotions; metadata",
              "gld_delivery_metrics, gld_cancellation_metrics, gld_promotion_metrics, gld_quality_summary",
              "Business / Marketing / Data Engineer workspaces"),
    FileEntry("src/transformations/gold/run.py", "3", "The gold stage: build the 12 Gold tables in order; typed Gold "
              "reader", "data/silver/", "data/gold/gld_*", "pipeline stage gold"),
    FileEntry("src/transformations/gold/catalog.py", "3", "Render the Gold catalog and the metric definitions",
              "Gold and ML table declarations, METRICS", "docs/gold_catalog.md, docs/metric_definitions.md",
              "scripts/build_docs.py"),

    # ------------------------------------------------------------------ src/ml
    FileEntry("src/ml/tables.py", "4", "Declarations of the Gold tables written by the ML stage, plus pandas read / write",
              "—", "ML table schemas", "every ML module, publish, check scripts"),
    FileEntry("src/ml/evaluation.py", "4", "Forecast accuracy metrics (MAE, RMSE, WAPE, bias, band coverage)",
              "actual / forecast series", "metric dicts", "forecasting"),
    FileEntry("src/ml/forecasting/model.py", "4", "Gradient-boosting demand model (Poisson + quantile band) and the "
              "recursive 7-day forecaster", "feature rows", "ForecastModel, forecasts", "forecasting/run.py"),
    FileEntry("src/ml/forecasting/run.py", "4", "Train, backtest on September, refit, 7-day forecast, SKU split, "
              "metrics, importance, model registry", "gld_demand_features, gld_inventory_daily, "
              "gld_daily_category_sales", "gld_demand_predictions, gld_sku_demand_forecast, gld_forecast_metrics, "
              "gld_forecast_feature_importance, data/ml/models/", "pipeline stage ml",
              "python -m scripts.run_pipeline --stages ml"),
    FileEntry("src/ml/stockout/run.py", "4", "Stockout risk tiers with reason codes, replenishment quantities, "
              "September backtest vs a naive rule", "gld_inventory_daily, gld_sku_demand_forecast",
              "gld_stockout_risk, gld_replenishment, gld_stockout_backtest", "pipeline stage ml, Inventory workspace"),
    FileEntry("src/ml/lost_sales.py", "5", "Lost-sales estimate on stockout days (expected − sold × price)",
              "gld_inventory_daily, slv_products", "gld_lost_sales", "pipeline stage ml, Inventory explorer"),
    FileEntry("src/ml/anomaly.py", "5", "Sales anomaly detection: store outages (hourly orders), demand spikes "
              "(product × store × day), payment failures (hourly failed payments + ERROR logs); Poisson p-values "
              "against the previous 28 days", "slv_orders, slv_order_items, slv_payments, slv_application_logs",
              "gld_sales_anomalies, gld_anomaly_series", "pipeline stage ml, Business workspace"),
    FileEntry("src/ml/segmentation.py", "5", "Customer segmentation: K-means on behaviour + category mix, k by "
              "silhouette, stability check, segments named from measured traits, campaign ideas",
              "gld_customer_360, gld_customer_category", "segment assignments, profiles, k selection",
              "src/ml/marketing.py"),
    FileEntry("src/ml/recommendations.py", "5", "Top-10 recommendations (buy again + often bought with + popularity, "
              "fixed weights) with a September backtest vs popularity and buy-again baselines",
              "slv_orders, slv_order_items", "recommendations, backtest metrics", "src/ml/marketing.py"),
    FileEntry("src/ml/marketing.py", "5", "Marketing step of the ml stage: segmentation, basket rules, "
              "recommendations, descriptive retention; model registry", "Gold customer tables, gld_basket_pairs, "
              "Silver orders / items / customers", "gld_customer_segments, gld_segment_profiles, "
              "gld_segmentation_selection, gld_basket_rules, gld_recommendations, gld_recommendation_metrics, "
              "gld_retention_cohorts, gld_customer_retention", "pipeline stage ml, Marketing workspace"),

    # ------------------------------------------------------------------ src/orchestration
    FileEntry("src/rag/composer.py", "6", "Template answers in the house style: headline points, table, 1–2 quoted "
              "sentences with citations, understood-as line, sources; help and out-of-scope replies",
              "ToolResult, hits", "Answer", "src/rag/assistant.py"),
    FileEntry("src/rag/entities.py", "6", "Turn words in a question into tool parameters: stores, cities, categories, "
              "products, risk tiers, detectors, top-N, periods relative to the end of the data", "question, published "
              "lookups (dim tables)", "Entities", "business assistant"),
    FileEntry("src/rag/router.py", "6", "Rule-based router: data / policy / method / hybrid / insufficient (why) / "
              "help / out-of-scope, and the tool by its trigger phrases", "question, entities", "Route",
              "src/rag/assistant.py"),
    FileEntry("src/rag/tools.py", "6", "Whitelisted data tools (16) wrapping role-checked queries: validated inputs "
              "(Pydantic + lookups + data period), headline numbers, table, source, as-of; no customer-level data",
              "Entities / parameters, role", "ToolResult", "business assistant"),
    FileEntry("src/rag/llm.py", "6", "Optional LLM layer (default: free Groq + open-weight gpt-oss-120b; any OpenAI-compatible provider or Claude): rephrases the template answer's evidence only; code verifies "
              "every number and citation, caps length, and falls back silently to the template (stdlib HTTP, no package)",
              "Answer (template), optional API key", "Answer (verified LLM text or template) + mode",
              "src/rag/assistant.py, check_phase6 --mode llm"),
    FileEntry("src/rag/retrieval.py", "6", "BM25 keyword search over the knowledge chunks (implemented in-house, no "
              "vector database), synonym expansion, doc-type filter, top-3 with a calibrated minimum score, citations",
              "rag_chunks (snapshot)", "ranked hits with citations", "business assistant"),
    FileEntry("src/orchestration/tracking.py", "2", "Run tracking: pipeline / stage / table runs, file loads, lineage, "
              "quality and model registry tables (CSV, one file per run)", "—", "data/metadata/meta_*/",
              "every stage, check scripts"),
    FileEntry("src/orchestration/pipeline.py", "2", "Pipeline runner: resolve the generation run, run stages in order, "
              "record the outcome", "stage list, configs", "stage results, run metadata", "scripts/run_pipeline.py, tests"),
    FileEntry("src/orchestration/publish.py", "4", "The publish stage: copy app tables to data/demo/ with schema and "
              "manifest, size-checked, swapped in atomically; includes the assistant's knowledge chunks",
              "Gold + ML tables, Silver lookups, policies + docs", "data/demo/*.csv (incl. rag_chunks.csv), "
              "snapshot_schema.csv, snapshot_manifest.csv", "pipeline stage publish"),

    # ------------------------------------------------------------------ src/serving
    FileEntry("src/rag/assistant.py", "6", "The business assistant: question → entities → route → tool and / or "
              "retrieval → composed answer; refuses other workspaces' data; log record per answer",
              "question, role, retriever, lookups", "Answer", "Assistant page, check_phase6"),
    FileEntry("src/rag/chunking.py", "6", "Knowledge base for the business assistant: split policies, metric "
              "definitions and model cards into citable chunks (section-based, 160-word windows, 30-word overlap)",
              "policies/*.md, docs/metric_definitions.md, docs/05/06/08/09/10", "chunk table (rag_chunks)",
              "src/orchestration/publish.py"),
    FileEntry("src/serving/reliability.py", "6", "Forecast reliability bands per category (High / Medium / Low) "
              "and the action for each — one definition for the app and the assistant", "category WAPE",
              "reliability label, action", "app/components/insights.py, src/rag/tools.py"),
    FileEntry("src/serving/metrics.py", "3", "The single definition of every business metric (+ Spark helpers)",
              "—", "METRICS, line_revenue(), ratio()", "Gold, docs, app"),
    FileEntry("src/serving/permissions.py", "4", "Roles, workspaces and the access check used inside data functions",
              "—", "require(), allowed_workspaces()", "queries.py, app"),
    FileEntry("src/serving/db.py", "4", "Load the published snapshot into in-memory DuckDB (typed from the schema file)",
              "data/demo/", "Snapshot (query interface)", "queries.py"),
    FileEntry("src/serving/queries.py", "4", "The only data functions app pages may call; each checks the role and runs a "
              "parameterised DuckDB query", "Snapshot", "DataFrames / dicts for pages", "app views, check scripts"),

    # ------------------------------------------------------------------ app
    FileEntry("app/Home.py", "4", "Streamlit entry point: login page until signed in, then the user lands directly in "
              "their own workspace (admin: overview + all workspaces)", "secrets, role", "navigation", "users", "streamlit run app/Home.py"),
    FileEntry("app/components/auth.py", "4", "Demo login (bcrypt hashes from Streamlit secrets) and the two-column login page",
              ".streamlit/secrets.toml",
              "session user", "Home.py, ui.py"),
    FileEntry("app/components/insights.py", "5", "Plain-language summaries of what a chart shows (forecast, SKU "
              "stock) and High / Medium / Low colour-coding for tables", "query results", "sentences, tables, styled "
              "tables", "inventory.py, business.py"),
    FileEntry("app/components/personas.py", "5", "Persona / workspace descriptions (icon, title, tagline, use "
              "cases) shared by the login page, headers and admin overview", "—", "PERSONAS", "auth.py, ui.py, Home.py, "
              "views"),
    FileEntry("app/components/ui.py", "4", "Styling, persona header band, tab question line, sidebar profile + sign out, "
              "workspace guard, freshness banner, advisory note", "session user, manifest",
              "page elements", "every view"),
    FileEntry("app/components/charts.py", "4", "Plotly charts (forecast, stock, explorer, importance)", "query results",
              "figures", "views"),
    FileEntry("app/views/welcome.py", "4", "Admin overview (admin landing page): every workspace with use cases and links, "
              "snapshot facts", "snapshot manifest",
              "page", "Home.py"),
    FileEntry("app/views/inventory.py", "4", "Inventory & Supply Chain workspace: overview, forecasting, stockout & "
              "replenishment, inventory explorer", "src/serving/queries.py (inventory functions)", "page", "Home.py"),
    FileEntry("app/views/assistant.py", "6", "Assistant page (every persona): suggested questions, chat, route badge, "
              "answer table, Evidence & sources, mode; index cached per snapshot", "src/rag (assistant), session",
              "page", "Home.py"),
    FileEntry("app/views/business.py", "5", "Business & Revenue workspace: sales & revenue performance, delivery & "
              "operations, anomaly detection", "src/serving/queries.py (business functions)", "page", "Home.py"),
    FileEntry("app/views/engineering.py", "5", "Data Engineer landing page — workspace on hold, lists the planned "
              "use cases", "—", "page", "Home.py"),
    FileEntry("app/views/marketing.py", "5", "Customer Growth & Marketing workspace: segments, basket & affinity, "
              "recommendations, retention (descriptive), promotion effectiveness",
              "src/serving/queries.py (marketing functions)", "page", "Home.py"),

    # ------------------------------------------------------------------ scripts
    FileEntry("scripts/run_pipeline.py", "2", "Run pipeline stages from the command line", "stage names",
              "stage outputs + summary", "users", "python -m scripts.run_pipeline --stages ingest,silver,gold,ml,publish"),
    FileEntry("scripts/check_bronze.py", "2", "Bronze completion report (9 checks)", "Bronze, manifest, metadata",
              "console report", "users", "python -m scripts.check_bronze"),
    FileEntry("scripts/check_silver.py", "2", "Silver completion report: row accounting, no dirty values left, detected "
              "vs injected (10 checks)", "Silver, quarantine, ground truth", "console report", "users, tests",
              "python -m scripts.check_silver"),
    FileEntry("scripts/check_gold.py", "3", "Gold completion report: reconciliation with Silver, inventory continuity, "
              "leakage, planted signals (10 checks)", "Gold, Silver, ground truth", "console report", "users, tests",
              "python -m scripts.check_gold"),
    FileEntry("scripts/check_ml.py", "4", "Phase 4 report: forecast vs baselines, bands, registry, stockout backtest, "
              "app snapshot (12 checks)", "ML tables, metadata, snapshot, ground truth", "console report",
              "users, tests", "python -m scripts.check_ml"),
    FileEntry("scripts/check_phase5.py", "5", "Phase 5 report, section per step; PASS / LIMIT / FAIL",
              "Phase 5 tables, snapshot, ground truth", "console report", "users", "python -m scripts.check_phase5"),
    FileEntry("scripts/calibrate_retrieval.py", "6", "Calibrate the retrieval threshold on the practice questions "
              "(never on the evaluation set)", "data/demo/rag_chunks.csv, tests/rag/dev_questions.yaml",
              "console table + suggested MIN_SCORE", "users", "python -m scripts.calibrate_retrieval"),
    FileEntry("scripts/check_phase6.py", "6", "Phase 6 evaluation of the assistant: 40-question gold set + 5 role "
              "checks against fixed bars (routing, hit@3, numbers vs independent SQL, citations, refusal, roles)",
              "tests/rag/questions.yaml, snapshot", "console report, data/metadata/meta_rag_runs/<run>.csv", "users",
              "python -m scripts.check_phase6"),
    FileEntry("scripts/build_docs.py", "1", "Regenerate every generated document", "registries, specs, declarations",
              "docs/data_dictionary.md, transformation_catalog.md, gold_catalog.md, metric_definitions.md, "
              "file_registry.md", "users, tests", "python -m scripts.build_docs"),
    FileEntry("scripts/build_data_dictionary.py", "1", "Compatibility alias for build_docs", "—", "same as build_docs",
              "users", "python -m scripts.build_data_dictionary"),
    FileEntry("scripts/export_flat_tables.py", "2", "One flat CSV per table for review / presentation",
              "Bronze, Silver or Gold", "data_sep/, data_sep_silver/, data_sep_gold/", "users",
              "python -m scripts.export_flat_tables --layer silver"),
    FileEntry("scripts/create_demo_secrets.py", "4", "Create demo logins (bcrypt hashes) for the app", "—",
              ".streamlit/secrets.toml (git-ignored)", "users", "python -m scripts.create_demo_secrets"),

    # ------------------------------------------------------------------ tests
    FileEntry("tests/conftest.py", "1", "Shared fixtures: small generation run, Spark session, pipeline / silver / gold / "
              "app environments in temp folders", "small profile", "fixtures", "all tests"),
    FileEntry("tests/unit/test_config.py", "1", "Profiles load; medium targets match the plan; validation errors",
              "configs", "pass / fail", "pytest"),
    FileEntry("tests/unit/test_io.py", "1", "CSV round-trip keeps commas, quotes, empties; raw malformed lines",
              "—", "pass / fail", "pytest"),
    FileEntry("tests/unit/test_dirty_data.py", "1", "Dirty budget = 10%; every configured mutation applies; conflicting "
              "duplicates differ only in formatting", "small run", "pass / fail", "pytest"),
    FileEntry("tests/unit/test_data_dictionary.py", "1", "Every column / rule / derived column documented; generated docs "
              "up to date", "registries", "pass / fail", "pytest"),
    FileEntry("tests/unit/test_file_registry.py", "5", "Every project file is registered; no stale entries",
              "file system, REGISTRY", "pass / fail", "pytest"),
    FileEntry("tests/unit/test_stockout_rules.py", "4", "Risk tiers and the replenishment formula on hand-made cases",
              "—", "pass / fail", "pytest"),
    FileEntry("tests/unit/test_lost_sales.py", "5", "Lost-sales arithmetic on hand-made SKU histories", "—",
              "pass / fail", "pytest"),
    FileEntry("tests/unit/test_anomaly.py", "5", "Each anomaly detector catches its hand-made event and stays quiet on "
              "normal data", "—", "pass / fail", "pytest"),
    FileEntry("tests/unit/test_insights.py", "5", "Chart summaries and tier colours on hand-made data", "—",
              "pass / fail", "pytest"),
    FileEntry("tests/unit/test_chunking.py", "6", "Chunking rules on hand-made markdown and on the real knowledge base",
              "policies, docs", "pass / fail", "pytest"),
    FileEntry("tests/unit/test_retrieval.py", "6", "Tokenizer, synonyms, BM25 ranking, type filter, threshold, "
              "citations; core questions on the real knowledge base", "hand-made chunks, policies, docs",
              "pass / fail", "pytest"),
    FileEntry("tests/unit/test_entities.py", "6", "Entity extraction on hand-made lookups: stores, cities, categories, "
              "products, tiers, periods", "—", "pass / fail", "pytest"),
    FileEntry("tests/unit/test_router.py", "6", "Routes and tool choice for 16 phrasings, whole-word matching, quote "
              "selection", "—", "pass / fail", "pytest"),
    FileEntry("tests/unit/test_llm.py", "6", "LLM layer with a fake client (no network): verified reply shown, invented "
              "number / missing citation rejected, errors fall back, refusals never rephrased, key handling",
              "—", "pass / fail", "pytest"),
    FileEntry("tests/unit/test_marketing.py", "5", "Segment naming, basket rules both directions, recommendation "
              "metrics and retention status on hand-made data", "—", "pass / fail", "pytest"),
    FileEntry("tests/integration/test_generation.py", "1", "Counts, 90% clean, consistency rules C1–C11, landing files, "
              "determinism, planted signals", "small run", "pass / fail", "pytest"),
    FileEntry("tests/integration/test_spark_smoke.py", "2", "Spark session, Python workers, typed CSV round-trip",
              "—", "pass / fail", "pytest"),
    FileEntry("tests/integration/test_bronze.py", "2", "Bronze completeness, idempotency, raw values preserved, metadata, "
              "stream micro-batches", "small run", "pass / fail", "pytest"),
    FileEntry("tests/integration/test_silver.py", "2", "Silver report at 100%, cascade, primary rule, typed read-back, "
              "idempotent rebuild", "small run", "pass / fail", "pytest"),
    FileEntry("tests/integration/test_late_data.py", "2", "A late record is ingested, flagged late and dated by event time",
              "small run copy", "pass / fail", "pytest"),
    FileEntry("tests/integration/test_gold.py", "3", "Gold core checks, a hand-computed store-day, typed reads, "
              "idempotent rebuild", "small run", "pass / fail", "pytest"),
    FileEntry("tests/integration/test_ml.py", "4", "Forecast structure, future forecast, SKU split, no peeking at the "
              "future", "small run", "pass / fail", "pytest"),
    FileEntry("tests/app/test_assistant.py", "6", "The assistant end to end on a real snapshot: every route, numbers "
              "equal the dashboard, citations, refusal of other workspaces' data with no number leak",
              "small run snapshot", "pass / fail", "pytest"),
    FileEntry("tests/app/test_rag_tools.py", "6", "Assistant data tools on a real snapshot: per-role tool lists, every "
              "tool runs with source and no customer ids, role refusals, input validation, numbers equal the dashboards",
              "small run snapshot", "pass / fail", "pytest"),
    FileEntry("tests/app/test_app.py", "4", "Snapshot publish, role checks in every data function, login, workspace "
              "pages render / are blocked", "small run snapshot", "pass / fail", "pytest"),
)
